# Generated by Django 3.2.13 on 2022-07-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='input',
            field=models.TextField(blank=True, default=''),
        ),
    ]
