# Generated by Django 3.2.13 on 2022-08-01 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hits',
        ),
    ]
