# Generated by Django 3.2.13 on 2022-08-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_post_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(null=True, upload_to='uploaded/'),
        ),
    ]
